version: "3.9"

services:
    app:
        build:
            context: ./docker
            args:
                UID: 1000
                GID: 1000
        container_name: shopping-app
        ports:
            - "8070:8000"
        volumes:
            - ".:/sources"
            - "~/.ssh:/home/dev/.ssh"

    redis:
        image: "redis:latest"

    database:
        image: "mariadb:10.6"
        ports:
            - '3376:3306'
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=54adW2eq5DWepe

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8071:80"
        environment:
            - PMA_HOST=database
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=54adW2eq5DWepe

volumes:
    db-data:
